@echo off
echo Starting Flutter App on Android Device...
echo.
echo Cleaning previous build...
flutter clean
echo.
echo Getting dependencies...
flutter pub get
echo.
echo Running app on device SM A166P...
flutter run -d "R94Y30GLL5L" --debug
pause