@echo off
echo Testing Flutter App with Hot Reload...
echo.
echo Cleaning previous build...
flutter clean
echo.
echo Getting dependencies...
flutter pub get
echo.
echo Running app with hot reload on device SM A166P...
flutter run -d "R94Y30GLL5L" --debug --hot
pause